### Inscription d'un utilisateur
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Darryl",
    "email": "tchapdadarryl97@gmail.com",
    "password": "darryl1997"
}


### Connexion d'un utilisateur
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
      "email": "tchapdadarryl97@gmail.com",
    "password": "darryl1997"
}

### fonction pour deconnecter un utilisateur 
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

###  fonction pour afficher un utilisateur 
GET http://localhost:5000/api/auth/me
Content-Type: application/json


###  fonction pour afficher les utiliseurs 
GET http://localhost:5000/api/users


###
GET http://localhost:5000/api/users/1
Content-Type: application/json

